version: 0.2

phases:
  install:
    runtime-versions:
      android: 30
      java: corretto11
  pre_build:
    commands:
      - chmod +x ./gradlew
  build:
    commands:
      - ./gradlew assembleDebug

