version: 0.2

phases:
  install:
    runtime-versions:
      android: 30
      java: corretto11
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
    - './android/app/build/outputs/**/*.apk'
  discard-paths: yes