version: 0.2

batch:
  fast-fail: false
  build-graph:
    - identifier: unitTests
      buildspec: buildtests.yml
      env:
        variables:
          BUILD_ID: unitTests
      ignore-failure: false

    - identifier: buildreports
      buildspec: buildreports.yml
      env:
        variables:
          BUILD_ID: reports
      depend-on:
        - unitTests

phases:
  install:
    runtime-versions:
      android: 29
      java: corretto8
  pre_build:
    commands:
      - chmod +x ./gradlew
  build:
    commands:
      - ./gradlew assembleDebug

